/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UMS;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author sharvan
 */
public class ADDCOURSE extends javax.swing.JFrame {

    /**
     * Creates new form ADDCOURSE
     */
    public ADDCOURSE() {
        initComponents();
        
        tstno.setBackground(new java.awt.Color(0,0,0,1));
        tpass.setBackground(new java.awt.Color(0,0,0,1));
        S12223.setBackground(new java.awt.Color(0,0,0,1));
        S12233.setBackground(new java.awt.Color(0,0,0,1));
        S12213.setBackground(new java.awt.Color(0,0,0,1));
        S12242.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        msg = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        back = new javax.swing.JButton();
        S12233 = new javax.swing.JCheckBox();
        S12223 = new javax.swing.JCheckBox();
        S12213 = new javax.swing.JCheckBox();
        S12242 = new javax.swing.JCheckBox();
        course = new javax.swing.JLabel();
        tpass = new javax.swing.JPasswordField();
        pass = new javax.swing.JLabel();
        tstno = new javax.swing.JTextField();
        stno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 230));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(null);

        msg.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(msg);
        msg.setBounds(380, 510, 370, 30);

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        update.setForeground(new java.awt.Color(0, 204, 255));
        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(601, 580, 90, 27);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(0, 204, 255));
        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(700, 580, 71, 27);

        S12233.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S12233.setForeground(new java.awt.Color(0, 186, 255));
        S12233.setText("  SENG 12233 - object oriented programming");
        jPanel1.add(S12233);
        S12233.setBounds(380, 380, 370, 23);

        S12223.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S12223.setForeground(new java.awt.Color(0, 186, 255));
        S12223.setText("  SENG 12223 - database design and development");
        jPanel1.add(S12223);
        S12223.setBounds(380, 400, 370, 23);

        S12213.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S12213.setForeground(new java.awt.Color(0, 186, 255));
        S12213.setText("  SENG 12213 - data structures and algorithms");
        jPanel1.add(S12213);
        S12213.setBounds(380, 420, 370, 23);

        S12242.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S12242.setForeground(new java.awt.Color(0, 186, 255));
        S12242.setText("  SENG 12242 - management for engineering");
        jPanel1.add(S12242);
        S12242.setBounds(380, 440, 370, 23);

        course.setFont(new java.awt.Font("Bungee Inline", 0, 18)); // NOI18N
        course.setForeground(new java.awt.Color(0, 204, 255));
        course.setText("courses");
        jPanel1.add(course);
        course.setBounds(380, 340, 170, 30);

        tpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tpass.setForeground(new java.awt.Color(0, 204, 255));
        tpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));
        jPanel1.add(tpass);
        tpass.setBounds(380, 290, 240, 40);

        pass.setFont(new java.awt.Font("Bungee Inline", 0, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 204, 255));
        pass.setText("password");
        jPanel1.add(pass);
        pass.setBounds(380, 250, 170, 30);

        tstno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tstno.setForeground(new java.awt.Color(0, 204, 255));
        tstno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));
        jPanel1.add(tstno);
        tstno.setBounds(380, 190, 240, 40);

        stno.setFont(new java.awt.Font("Bungee Inline", 0, 18)); // NOI18N
        stno.setForeground(new java.awt.Color(0, 204, 255));
        stno.setText("Student no");
        jPanel1.add(stno);
        stno.setBounds(380, 160, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharvan\\Pictures\\UOKbgr.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String username = tstno.getText();
        String pass = String.valueOf(tpass.getPassword());
        String[] cs = new String[4];
        int i, count = 0;
        
        DBConnection DBC = new DBConnection();
        try{
            Statement stmt=DBC.getConnection().createStatement();
            ResultSet rs=stmt.executeQuery("SELECT * FROM Student WHERE Stu_no='"+username+"' AND Password='"+pass+"'");
            if(rs.next())
            {
                PreparedStatement pst =DBC.getConnection().prepareStatement("DELETE FROM Subject WHERE Stu_no=?");
                pst.setString(1, username);
                pst.execute();
                
                if(S12233.isSelected())
                {
                    cs[count]="SENG 12233 - OBJECT ORIENTED PROGRAMMING";
                    count++;
                }
                if(S12223.isSelected())
                {
                    cs[count]="SENG 12223 - DATABASE DESIGN AND DEVELOPMENT";
                    count++;
                }
                if(S12213.isSelected())
                {
                    cs[count]="SENG 12213 - DATA STRUCTURES AND ALGORITHM";
                    count++;
                }
                if(S12242.isSelected())
                {
                    cs[count]="SENG 12242 - MANAGEMENT FOR ENGINEERING";
                    count++;
                }
                
                for(i=0;i<count;i++)
                {
                PreparedStatement pstt =DBC.getConnection().prepareStatement("INSERT INTO Subject VALUES (?,?)");
                pstt.setString(1,username);
                pstt.setString(2,cs[i]);
                pstt.executeUpdate();
                
                }
                JOptionPane.showMessageDialog(this, "Successfully Updated", "Update", 1);
                
                new Studetail(username,pass).setVisible(true);
                this.dispose();
            }
            else{
                msg.setText("Incorrect Username Or Password");
                tstno.setText(null);
                tpass.setText(null);
            }
            
        }catch(Exception e){ System.out.println(e);    
        }         // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new STSIGNIN().setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADDCOURSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADDCOURSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADDCOURSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADDCOURSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDCOURSE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox S12213;
    private javax.swing.JCheckBox S12223;
    private javax.swing.JCheckBox S12233;
    private javax.swing.JCheckBox S12242;
    private javax.swing.JButton back;
    private javax.swing.JLabel course;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel stno;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tstno;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
