/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UMS;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author sharvan
 */
public class LECSIGNUP extends javax.swing.JFrame {

    /**
     * Creates new form LECSIGNUP
     */
    public LECSIGNUP() {
        initComponents();
        tname.setBackground(new java.awt.Color(0,0,0,1));
        tage.setBackground(new java.awt.Color(0,0,0,1));
        tlecid.setBackground(new java.awt.Color(0,0,0,1));
        tcontactno.setBackground(new java.awt.Color(0,0,0,1));
        temail.setBackground(new java.awt.Color(0,0,0,1));
        male.setBackground(new java.awt.Color(0,0,0,1));
        female.setBackground(new java.awt.Color(0,0,0,1));
        tpass.setBackground(new java.awt.Color(0,0,0,1));
        trepass.setBackground(new java.awt.Color(0,0,0,1));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        register = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        y4s2 = new javax.swing.JComboBox<>();
        S42 = new javax.swing.JLabel();
        y2s2 = new javax.swing.JComboBox<>();
        S22 = new javax.swing.JLabel();
        y4s1 = new javax.swing.JComboBox<>();
        S41 = new javax.swing.JLabel();
        S32 = new javax.swing.JLabel();
        y3s2 = new javax.swing.JComboBox<>();
        y3s1 = new javax.swing.JComboBox<>();
        S31 = new javax.swing.JLabel();
        y2s1 = new javax.swing.JComboBox<>();
        S21 = new javax.swing.JLabel();
        y1s2 = new javax.swing.JComboBox<>();
        Y4 = new javax.swing.JLabel();
        Y3 = new javax.swing.JLabel();
        Y2 = new javax.swing.JLabel();
        S12 = new javax.swing.JLabel();
        S11 = new javax.swing.JLabel();
        Y1 = new javax.swing.JLabel();
        y1s1 = new javax.swing.JComboBox<>();
        course = new javax.swing.JLabel();
        trepass = new javax.swing.JPasswordField();
        repass = new javax.swing.JLabel();
        tpass = new javax.swing.JPasswordField();
        pass = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        sex = new javax.swing.JLabel();
        eg = new javax.swing.JLabel();
        tcontactno = new javax.swing.JTextField();
        contactno = new javax.swing.JLabel();
        tage = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        tlecid = new javax.swing.JTextField();
        lecid = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 230));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(null);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(0, 204, 255));
        back.setText("BACK");
        jPanel1.add(back);
        back.setBounds(720, 600, 73, 25);

        register.setBackground(new java.awt.Color(0, 0, 0));
        register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        register.setForeground(new java.awt.Color(0, 204, 255));
        register.setText("REGISTER");
        register.setToolTipText("");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register);
        register.setBounds(587, 600, 110, 25);

        exit.setBackground(new java.awt.Color(0, 0, 0));
        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 204, 255));
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(720, 600, 67, 25);

        y4s2.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        y4s2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SENG 42213", "SENG 42223", "SENG 42233", "SENG 42242", "NONE" }));
        y4s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y4s2ActionPerformed(evt);
            }
        });
        jPanel1.add(y4s2);
        y4s2.setBounds(720, 510, 100, 20);

        S42.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S42.setForeground(new java.awt.Color(255, 204, 0));
        S42.setText("SEMESTER 2");
        jPanel1.add(S42);
        S42.setBounds(720, 490, 80, 15);

        y2s2.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        y2s2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SENG 22213", "SENG 22223", "SENG 22233", "SENG 22242", "NONE" }));
        y2s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y2s2ActionPerformed(evt);
            }
        });
        jPanel1.add(y2s2);
        y2s2.setBounds(440, 510, 100, 20);

        S22.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S22.setForeground(new java.awt.Color(255, 204, 0));
        S22.setText("SEMESTER 2");
        jPanel1.add(S22);
        S22.setBounds(440, 490, 80, 15);

        y4s1.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        y4s1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SENG 41213", "SENG 41223", "SENG 41233", "SENG 41242", "NONE" }));
        y4s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y4s1ActionPerformed(evt);
            }
        });
        jPanel1.add(y4s1);
        y4s1.setBounds(720, 450, 100, 20);

        S41.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S41.setForeground(new java.awt.Color(255, 204, 0));
        S41.setText("SEMESTER 1");
        jPanel1.add(S41);
        S41.setBounds(720, 430, 80, 15);

        S32.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S32.setForeground(new java.awt.Color(255, 204, 0));
        S32.setText("SEMESTER 1");
        jPanel1.add(S32);
        S32.setBounds(580, 490, 80, 15);

        y3s2.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        y3s2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SENG 32213", "SENG 32223", "SENG 32233", "SENG 32242", "NONE" }));
        y3s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y3s2ActionPerformed(evt);
            }
        });
        jPanel1.add(y3s2);
        y3s2.setBounds(580, 510, 100, 20);

        y3s1.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        y3s1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SENG 31213", "SENG 31223", "SENG 31233", "SENG 31242", "NONE" }));
        y3s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y3s1ActionPerformed(evt);
            }
        });
        jPanel1.add(y3s1);
        y3s1.setBounds(580, 450, 100, 20);

        S31.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S31.setForeground(new java.awt.Color(255, 204, 0));
        S31.setText("SEMESTER 1");
        jPanel1.add(S31);
        S31.setBounds(580, 430, 80, 15);

        y2s1.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        y2s1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SENG 21213", "SENG 21223", "SENG 21233", "SENG 21242", "NONE" }));
        y2s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y2s1ActionPerformed(evt);
            }
        });
        jPanel1.add(y2s1);
        y2s1.setBounds(440, 450, 100, 20);

        S21.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S21.setForeground(new java.awt.Color(255, 204, 0));
        S21.setText("SEMESTER 1");
        jPanel1.add(S21);
        S21.setBounds(440, 430, 80, 15);

        y1s2.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        y1s2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SENG 12213", "SENG 112223", "SENG 11=2233", "SENG 12242", "NONE" }));
        y1s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y1s2ActionPerformed(evt);
            }
        });
        jPanel1.add(y1s2);
        y1s2.setBounds(310, 510, 100, 20);

        Y4.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        Y4.setForeground(new java.awt.Color(0, 204, 255));
        Y4.setText("YEAR 4");
        jPanel1.add(Y4);
        Y4.setBounds(720, 400, 60, 18);

        Y3.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        Y3.setForeground(new java.awt.Color(0, 204, 255));
        Y3.setText("YEAR 3");
        jPanel1.add(Y3);
        Y3.setBounds(580, 400, 60, 18);

        Y2.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        Y2.setForeground(new java.awt.Color(0, 204, 255));
        Y2.setText("YEAR 2");
        jPanel1.add(Y2);
        Y2.setBounds(440, 400, 60, 18);

        S12.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S12.setForeground(new java.awt.Color(255, 204, 0));
        S12.setText("SEMESTER 2");
        jPanel1.add(S12);
        S12.setBounds(310, 490, 80, 15);

        S11.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S11.setForeground(new java.awt.Color(255, 204, 0));
        S11.setText("SEMESTER 1");
        jPanel1.add(S11);
        S11.setBounds(310, 430, 80, 15);

        Y1.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        Y1.setForeground(new java.awt.Color(0, 204, 255));
        Y1.setText("YEAR 1");
        jPanel1.add(Y1);
        Y1.setBounds(310, 400, 60, 18);

        y1s1.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        y1s1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SENG 11213", "SENG 11223", "SENG 11233", "SENG 11242", "NONE" }));
        y1s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y1s1ActionPerformed(evt);
            }
        });
        jPanel1.add(y1s1);
        y1s1.setBounds(310, 450, 100, 20);

        course.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        course.setForeground(new java.awt.Color(0, 186, 255));
        course.setText("courses              :");
        jPanel1.add(course);
        course.setBounds(360, 360, 120, 20);

        trepass.setForeground(new java.awt.Color(255, 255, 255));
        trepass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        jPanel1.add(trepass);
        trepass.setBounds(700, 330, 110, 20);

        repass.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        repass.setForeground(new java.awt.Color(0, 186, 255));
        repass.setText("re-enter   :");
        jPanel1.add(repass);
        repass.setBounds(610, 330, 100, 20);

        tpass.setForeground(new java.awt.Color(255, 255, 255));
        tpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        jPanel1.add(tpass);
        tpass.setBounds(480, 330, 120, 20);

        pass.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 186, 255));
        pass.setText("password         :");
        jPanel1.add(pass);
        pass.setBounds(360, 330, 120, 20);

        temail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        temail.setForeground(new java.awt.Color(255, 255, 255));
        temail.setAlignmentX(5.0F);
        temail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        jPanel1.add(temail);
        temail.setBounds(480, 300, 330, 20);

        email.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(0, 204, 255));
        email.setText("e-mail                  :");
        jPanel1.add(email);
        email.setBounds(360, 300, 120, 20);

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        male.setForeground(new java.awt.Color(0, 186, 255));
        male.setText("male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male);
        male.setBounds(480, 270, 80, 20);

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        female.setForeground(new java.awt.Color(0, 186, 255));
        female.setText("female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female);
        female.setBounds(600, 270, 80, 20);

        sex.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        sex.setForeground(new java.awt.Color(0, 204, 255));
        sex.setText("sex                           :");
        jPanel1.add(sex);
        sex.setBounds(360, 270, 120, 20);

        eg.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        eg.setForeground(new java.awt.Color(0, 204, 255));
        eg.setText("eg: LEC_SE_02");
        jPanel1.add(eg);
        eg.setBounds(480, 180, 330, 20);

        tcontactno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tcontactno.setForeground(new java.awt.Color(255, 255, 255));
        tcontactno.setAlignmentX(5.0F);
        tcontactno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        jPanel1.add(tcontactno);
        tcontactno.setBounds(480, 240, 330, 20);

        contactno.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        contactno.setForeground(new java.awt.Color(0, 204, 255));
        contactno.setText("contact no      :");
        jPanel1.add(contactno);
        contactno.setBounds(360, 240, 120, 20);

        tage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tage.setForeground(new java.awt.Color(255, 255, 255));
        tage.setAlignmentX(5.0F);
        tage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        jPanel1.add(tage);
        tage.setBounds(480, 210, 330, 20);

        age.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        age.setForeground(new java.awt.Color(0, 204, 255));
        age.setText("age                           :");
        jPanel1.add(age);
        age.setBounds(360, 210, 120, 20);

        tlecid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tlecid.setForeground(new java.awt.Color(255, 255, 255));
        tlecid.setAlignmentX(5.0F);
        tlecid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        jPanel1.add(tlecid);
        tlecid.setBounds(480, 160, 330, 20);

        lecid.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        lecid.setForeground(new java.awt.Color(0, 204, 255));
        lecid.setText("lecturer id    :");
        jPanel1.add(lecid);
        lecid.setBounds(360, 160, 120, 20);

        tname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tname.setForeground(new java.awt.Color(255, 255, 255));
        tname.setAlignmentX(5.0F);
        tname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        jPanel1.add(tname);
        tname.setBounds(480, 130, 330, 20);

        name.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(0, 204, 255));
        name.setText("name                      :");
        jPanel1.add(name);
        name.setBounds(360, 130, 120, 20);

        head.setFont(new java.awt.Font("Bungee Inline", 0, 24)); // NOI18N
        head.setForeground(new java.awt.Color(255, 0, 51));
        head.setText("lecturer signup form");
        jPanel1.add(head);
        head.setBounds(390, 80, 315, 29);

        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharvan\\Pictures\\UOKbgr.jpg")); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(0, 0, 830, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed

    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void y1s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y1s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y1s1ActionPerformed

    private void y1s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y1s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y1s2ActionPerformed

    private void y2s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y2s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y2s1ActionPerformed

    private void y3s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y3s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y3s1ActionPerformed

    private void y4s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y4s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y4s1ActionPerformed

    private void y2s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y2s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y2s2ActionPerformed

    private void y4s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y4s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y4s2ActionPerformed

    private void y3s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y3s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y3s2ActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        String name = tname.getText();
        int age = Integer.parseInt(tage.getText());
        String email = temail.getText(); 
        int contactno = Integer.parseInt(tcontactno.getText());
        String lecid = tlecid.getText();
        String pass = new String(trepass.getPassword());
        String repass = new String(trepass.getPassword());
        String sex = null;
        String[] cmodule = new String[8];
        int count=0,i=0;
        
        if(male.isSelected())
        {
            sex="Male";
        }
        if(female.isSelected())
        {
            sex="Female";
        }
        
        cmodule[0]=y1s1.getSelectedItem().toString();
        cmodule[1]=y1s2.getSelectedItem().toString();
        cmodule[2]=y2s1.getSelectedItem().toString();
        cmodule[3]=y2s2.getSelectedItem().toString();
        cmodule[4]=y3s1.getSelectedItem().toString();
        cmodule[5]=y3s2.getSelectedItem().toString();
        cmodule[6]=y4s1.getSelectedItem().toString();
        cmodule[7]=y4s2.getSelectedItem().toString();

        if(pass.equals(repass))
        {
        
        try{
            DBConnection DBC = new DBConnection();
            PreparedStatement pst = DBC.getConnection().prepareStatement("INSERT INTO Lecturer VALUES (?,?,?,?,?,?,?)");
            pst.setString(1,lecid);
            pst.setString(2,name);
            pst.setInt(3, age);
            pst.setInt(4, contactno);
            pst.setString(5,sex);
            pst.setString(6,email);
            pst.setString(7,pass);
            
            pst.executeUpdate();
            
            for(i=0;i<8;i++)
            {
                PreparedStatement pstt4 =DBC.getConnection().prepareStatement("INSERT INTO CModule VALUES (?,?)");
                pstt4.setString(1,lecid);
                pstt4.setString(2,cmodule[i]);
                pstt4.executeUpdate();
                
            }
            
            JOptionPane.showMessageDialog(this, "Successfully Registered", "SignUP", 2);
            
            Statement stmt=DBC.getConnection().createStatement();
            ResultSet rs=stmt.executeQuery("SELECT * FROM Lecturer WHERE Lec_ID='"+lecid+"' AND Password='"+pass+"'");
            new LECDETAILS(lecid,pass).setVisible(true);
            this.dispose();
            
            
            DBC.getConnection().close();
            
        }catch(Exception e)
        {
            System.out.println(e);
            
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "PASSWORDS DO NOT MATCH", "SignUP", 1);
        }       // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LECSIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LECSIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LECSIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LECSIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LECSIGNUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel S11;
    private javax.swing.JLabel S12;
    private javax.swing.JLabel S21;
    private javax.swing.JLabel S22;
    private javax.swing.JLabel S31;
    private javax.swing.JLabel S32;
    private javax.swing.JLabel S41;
    private javax.swing.JLabel S42;
    private javax.swing.JLabel Y1;
    private javax.swing.JLabel Y2;
    private javax.swing.JLabel Y3;
    private javax.swing.JLabel Y4;
    private javax.swing.JLabel age;
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel contactno;
    private javax.swing.JLabel course;
    private javax.swing.JLabel eg;
    private javax.swing.JLabel email;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel head;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lecid;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pass;
    private javax.swing.JButton register;
    private javax.swing.JLabel repass;
    private javax.swing.JLabel sex;
    private javax.swing.JTextField tage;
    private javax.swing.JTextField tcontactno;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tlecid;
    private javax.swing.JTextField tname;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JPasswordField trepass;
    private javax.swing.JComboBox<String> y1s1;
    private javax.swing.JComboBox<String> y1s2;
    private javax.swing.JComboBox<String> y2s1;
    private javax.swing.JComboBox<String> y2s2;
    private javax.swing.JComboBox<String> y3s1;
    private javax.swing.JComboBox<String> y3s2;
    private javax.swing.JComboBox<String> y4s1;
    private javax.swing.JComboBox<String> y4s2;
    // End of variables declaration//GEN-END:variables
}
