/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UMS;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sharvan
 */
public class SIGNINLEC extends javax.swing.JFrame {

    /**
     * Creates new form SIGNINLEC
     */
    public SIGNINLEC() {
        initComponents();
        
        tlecid.setBackground(new java.awt.Color(0,0,0,1));
        tpass.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        eg = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        yet = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        signin = new javax.swing.JButton();
        tpass = new javax.swing.JPasswordField();
        password = new javax.swing.JLabel();
        tlecid = new javax.swing.JTextField();
        lecid = new javax.swing.JLabel();
        usericon = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 230));
        setUndecorated(true);
        setResizable(false);

        jPanel3.setLayout(null);

        eg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eg.setForeground(new java.awt.Color(0, 158, 206));
        eg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eg.setText("eg: LEC_SE_02");
        jPanel3.add(eg);
        eg.setBounds(450, 390, 240, 20);

        msg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        msg.setForeground(new java.awt.Color(204, 0, 51));
        jPanel3.add(msg);
        msg.setBounds(450, 604, 240, 30);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setForeground(new java.awt.Color(0, 158, 206));
        back.setText("<");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel3.add(back);
        back.setBounds(740, 10, 40, 23);

        exit.setBackground(new java.awt.Color(0, 0, 0));
        exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 158, 206));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel3.add(exit);
        exit.setBounds(783, 10, 40, 23);

        yet.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        yet.setForeground(new java.awt.Color(0, 158, 206));
        yet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yet.setText("-------- not registered yet !! --------");
        jPanel3.add(yet);
        yet.setBounds(450, 540, 240, 20);

        register.setBackground(new java.awt.Color(0, 0, 0));
        register.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        register.setForeground(new java.awt.Color(0, 158, 206));
        register.setText("register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel3.add(register);
        register.setBounds(450, 570, 240, 30);

        signin.setBackground(new java.awt.Color(0, 0, 0));
        signin.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        signin.setForeground(new java.awt.Color(0, 158, 206));
        signin.setText("sign in");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        jPanel3.add(signin);
        signin.setBounds(450, 490, 240, 30);

        tpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tpass.setForeground(new java.awt.Color(255, 255, 255));
        tpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 158, 208), 2));
        jPanel3.add(tpass);
        tpass.setBounds(450, 440, 240, 30);

        password.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(0, 158, 206));
        password.setText("password");
        jPanel3.add(password);
        password.setBounds(450, 410, 90, 30);

        tlecid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tlecid.setForeground(new java.awt.Color(255, 255, 255));
        tlecid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 158, 206), 2));
        jPanel3.add(tlecid);
        tlecid.setBounds(450, 360, 240, 30);

        lecid.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        lecid.setForeground(new java.awt.Color(0, 156, 206));
        lecid.setText("Lecturer ID");
        jPanel3.add(lecid);
        lecid.setBounds(450, 330, 100, 30);

        usericon.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharvan\\Pictures\\blue-user-icon.png")); // NOI18N
        jPanel3.add(usericon);
        usericon.setBounds(440, 60, 256, 260);

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharvan\\Pictures\\UOKbgr.jpg")); // NOI18N
        jPanel3.add(bg);
        bg.setBounds(0, 0, 830, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        SignUP Sp = new SignUP();
        Sp.setVisible(true);
        Sp.pack();
        Sp.setLocationRelativeTo(null);
        Sp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        String username = tlecid.getText();
        String pass = String.valueOf(tpass.getPassword());
        
        DBConnection DBC = new DBConnection();
        try{
            Statement stmt=DBC.getConnection().createStatement();
            ResultSet rs=stmt.executeQuery("SELECT * FROM Lecturer WHERE Lec_ID='"+username+"' AND Password='"+pass+"'");
            if(rs.next())
            {
                new LECDETAILS(username,pass).setVisible(true);
                this.dispose();
            }
            else{
                msg.setText("Incorrect Username Or Password");
                tlecid.setText(null);
                tpass.setText(null);
            }
            
        }catch(Exception e){ System.out.println(e);    
        }        // TODO add your handling code here:
    }//GEN-LAST:event_signinActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        LECSIGNUP LCsu = new LECSIGNUP();
        LCsu.setVisible(true);
        LCsu.pack();
        LCsu.setLocationRelativeTo(null);
        LCsu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGNINLEC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGNINLEC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGNINLEC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGNINLEC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGNINLEC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel eg;
    private javax.swing.JButton exit;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lecid;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel password;
    private javax.swing.JButton register;
    private javax.swing.JButton signin;
    private javax.swing.JTextField tlecid;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JLabel usericon;
    private javax.swing.JLabel yet;
    // End of variables declaration//GEN-END:variables
}
