/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UMS;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author sharvan
 */
public class STSIGNUP extends javax.swing.JFrame {

    /**
     * Creates new form STSIGNUP
     */
    public STSIGNUP() {
        initComponents();
        tname.setBackground(new java.awt.Color(0,0,0,1));
        tage.setBackground(new java.awt.Color(0,0,0,1));
        tstno.setBackground(new java.awt.Color(0,0,0,1));
        tcontactno.setBackground(new java.awt.Color(0,0,0,1));
        temail.setBackground(new java.awt.Color(0,0,0,1));
        male.setBackground(new java.awt.Color(0,0,0,1));
        female.setBackground(new java.awt.Color(0,0,0,1));
        tpass.setBackground(new java.awt.Color(0,0,0,1));
        trepass.setBackground(new java.awt.Color(0,0,0,1));
        S12223.setBackground(new java.awt.Color(0,0,0,1));
        S12233.setBackground(new java.awt.Color(0,0,0,1));
        S12213.setBackground(new java.awt.Color(0,0,0,1));
        S12242.setBackground(new java.awt.Color(0,0,0,1));
        register.setBackground(new java.awt.Color(0,0,0,1));
        reset.setBackground(new java.awt.Color(0,0,0,1));
        cancel.setBackground(new java.awt.Color(0,0,0,1));
        
    }
    
    public void validpass(String password)
    {
        if(password.length()>10 || password.length()<6)
        {
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "password must contain 6 - 10 characters !!", "SignUP", 2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        register = new javax.swing.JButton();
        S12242 = new javax.swing.JCheckBox();
        S12213 = new javax.swing.JCheckBox();
        S12223 = new javax.swing.JCheckBox();
        S12233 = new javax.swing.JCheckBox();
        course = new javax.swing.JLabel();
        trepass = new javax.swing.JPasswordField();
        repass = new javax.swing.JLabel();
        tpass = new javax.swing.JPasswordField();
        pass = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        sex = new javax.swing.JLabel();
        tcontactno = new javax.swing.JTextField();
        contactno = new javax.swing.JLabel();
        tstno = new javax.swing.JTextField();
        stno = new javax.swing.JLabel();
        tage = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        eg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 230));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jPanel3.setLayout(null);

        cancel.setFont(new java.awt.Font("Bungee Inline", 0, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(0, 186, 255));
        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel3.add(cancel);
        cancel.setBounds(680, 570, 130, 40);

        reset.setFont(new java.awt.Font("Bungee Inline", 0, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 186, 255));
        reset.setText("reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel3.add(reset);
        reset.setBounds(520, 570, 140, 40);

        register.setFont(new java.awt.Font("Bungee Inline", 0, 18)); // NOI18N
        register.setForeground(new java.awt.Color(0, 186, 255));
        register.setText("register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel3.add(register);
        register.setBounds(360, 570, 140, 40);

        S12242.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S12242.setForeground(new java.awt.Color(0, 186, 255));
        S12242.setText("  SENG 12242 - management for engineering");
        jPanel3.add(S12242);
        S12242.setBounds(460, 500, 370, 23);

        S12213.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S12213.setForeground(new java.awt.Color(0, 186, 255));
        S12213.setText("  SENG 12213 - data structures and algorithms");
        jPanel3.add(S12213);
        S12213.setBounds(460, 480, 370, 23);

        S12223.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S12223.setForeground(new java.awt.Color(0, 186, 255));
        S12223.setText("  SENG 12223 - database design and development");
        jPanel3.add(S12223);
        S12223.setBounds(460, 460, 370, 23);

        S12233.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        S12233.setForeground(new java.awt.Color(0, 186, 255));
        S12233.setText("  SENG 12233 - object oriented programming");
        jPanel3.add(S12233);
        S12233.setBounds(460, 440, 370, 23);

        course.setFont(new java.awt.Font("Bungee Inline", 0, 15)); // NOI18N
        course.setForeground(new java.awt.Color(0, 186, 255));
        course.setText("courses         :");
        jPanel3.add(course);
        course.setBounds(340, 440, 110, 30);

        trepass.setForeground(new java.awt.Color(0, 186, 255));
        trepass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 186, 255), 2));
        jPanel3.add(trepass);
        trepass.setBounds(700, 390, 110, 30);

        repass.setFont(new java.awt.Font("Bungee Inline", 0, 15)); // NOI18N
        repass.setForeground(new java.awt.Color(0, 186, 255));
        repass.setText("re-enter   :");
        jPanel3.add(repass);
        repass.setBounds(590, 390, 100, 30);

        tpass.setForeground(new java.awt.Color(0, 186, 255));
        tpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 186, 255), 2));
        jPanel3.add(tpass);
        tpass.setBounds(460, 390, 120, 30);

        pass.setFont(new java.awt.Font("Bungee Inline", 0, 15)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 186, 255));
        pass.setText("password    :");
        jPanel3.add(pass);
        pass.setBounds(340, 390, 110, 30);

        temail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        temail.setForeground(new java.awt.Color(0, 186, 255));
        temail.setAlignmentX(5.0F);
        temail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 186, 255), 2));
        jPanel3.add(temail);
        temail.setBounds(460, 340, 350, 30);

        email.setFont(new java.awt.Font("Bungee Inline", 0, 15)); // NOI18N
        email.setForeground(new java.awt.Color(0, 186, 255));
        email.setText("e-mail             :");
        jPanel3.add(email);
        email.setBounds(340, 340, 110, 30);

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        female.setForeground(new java.awt.Color(0, 186, 255));
        female.setText("female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel3.add(female);
        female.setBounds(580, 300, 100, 30);

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Bungee Inline", 0, 12)); // NOI18N
        male.setForeground(new java.awt.Color(0, 186, 255));
        male.setText("male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel3.add(male);
        male.setBounds(460, 300, 100, 30);

        sex.setFont(new java.awt.Font("Bungee Inline", 0, 15)); // NOI18N
        sex.setForeground(new java.awt.Color(0, 186, 255));
        sex.setText("sex                       :");
        jPanel3.add(sex);
        sex.setBounds(340, 300, 110, 30);

        tcontactno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tcontactno.setForeground(new java.awt.Color(0, 186, 255));
        tcontactno.setAlignmentX(5.0F);
        tcontactno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 186, 255), 2));
        jPanel3.add(tcontactno);
        tcontactno.setBounds(460, 260, 350, 30);

        contactno.setFont(new java.awt.Font("Bungee Inline", 0, 15)); // NOI18N
        contactno.setForeground(new java.awt.Color(0, 186, 255));
        contactno.setText("contact no  :");
        jPanel3.add(contactno);
        contactno.setBounds(340, 260, 110, 30);

        tstno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tstno.setForeground(new java.awt.Color(0, 186, 255));
        tstno.setAlignmentX(5.0F);
        tstno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 186, 255), 2));
        jPanel3.add(tstno);
        tstno.setBounds(460, 200, 350, 30);

        stno.setFont(new java.awt.Font("Bungee Inline", 0, 15)); // NOI18N
        stno.setForeground(new java.awt.Color(0, 186, 255));
        stno.setText("student no :");
        jPanel3.add(stno);
        stno.setBounds(340, 200, 110, 30);

        tage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tage.setForeground(new java.awt.Color(0, 186, 255));
        tage.setAlignmentX(5.0F);
        tage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 186, 255), 2));
        jPanel3.add(tage);
        tage.setBounds(460, 160, 350, 30);

        age.setFont(new java.awt.Font("Bungee Inline", 0, 15)); // NOI18N
        age.setForeground(new java.awt.Color(0, 186, 255));
        age.setText("age                       :");
        jPanel3.add(age);
        age.setBounds(340, 160, 110, 30);

        tname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tname.setForeground(new java.awt.Color(0, 186, 255));
        tname.setAlignmentX(5.0F);
        tname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 186, 255), 2));
        jPanel3.add(tname);
        tname.setBounds(460, 120, 350, 30);

        name.setFont(new java.awt.Font("Bungee Inline", 0, 15)); // NOI18N
        name.setForeground(new java.awt.Color(0, 186, 255));
        name.setText("name                   :");
        jPanel3.add(name);
        name.setBounds(340, 120, 110, 30);

        eg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eg.setForeground(new java.awt.Color(255, 255, 255));
        eg.setText("eg: SE_2017_037          * This will be used as User Name");
        jPanel3.add(eg);
        eg.setBounds(460, 230, 350, 20);

        jLabel1.setFont(new java.awt.Font("Bungee Inline", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("REGISTRATION FORM");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(350, 50, 420, 40);

        bground.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharvan\\Pictures\\UOKbgr.jpg")); // NOI18N
        bground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 186, 255), 4));
        jPanel3.add(bground);
        bground.setBounds(0, 0, 830, 650);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed

    }//GEN-LAST:event_maleActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        tname.setText(null);
        tage.setText(null);
        tstno.setText(null);
        tcontactno.setText(null);
        temail.setText(null);
        male.setSelected(false);
        female.setSelected(false);
        tpass.setText(null);
        trepass.setText(null);
        S12223.setSelected(false);
        S12233.setSelected(false);
        S12213.setSelected(false);
        S12242.setSelected(false);   // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        String name = tname.getText();
        int age = Integer.parseInt(tage.getText());
        String email = temail.getText(); 
        int contactno = Integer.parseInt(tcontactno.getText());
        String stno = tstno.getText();
        String pass = new String(trepass.getPassword());
        String repass = new String(trepass.getPassword());
        String sex = null;
        //String course = null;
        String[] cs = new String[4];
        int count=0,i=0;
        
        if(male.isSelected())
        {
            sex="Male";
        }
        if(female.isSelected())
        {
            sex="Female";
        }
        
            if(S12233.isSelected())
            {
                cs[count]="SENG 12233 - OBJECT ORIENTED PROGRAMMING";
                count++;
            }
            if(S12223.isSelected())
            {
                cs[count]="SENG 12223 - DATABASE DESIGN AND DEVELOPMENT";
                count++;
            }
            if(S12213.isSelected())
            {
                cs[count]="SENG 12213 - DATA STRUCTURES AND ALGORITHM";
                count++;
            }
            if(S12242.isSelected())
            {
                cs[count]="SENG 12242 - MANAGEMENT FOR ENGINEERING";
                count++;
            }
            
        
        //
        if(pass.equals(repass))
        {
        
        try{
            DBConnection DBC = new DBConnection();
            PreparedStatement pst = DBC.getConnection().prepareStatement("INSERT INTO Student VALUES (?,?,?,?,?,?,?)");
            pst.setString(1,stno);
            pst.setString(2,name);
            pst.setInt(3, age);
            pst.setString(4,sex);
            pst.setInt(5, contactno);
            pst.setString(6,email);
            pst.setString(7,pass);
            
            pst.executeUpdate();
            /*
            if(S12233.isSelected())
            {
                course="SENG 12233 - OBJECT ORIENTED PROGRAMMING";
                PreparedStatement pstt1 =DBC.getConnection().prepareStatement("INSERT INTO Subject VALUES (?,?)");
                pstt1.setString(1,stno);
                pstt1.setString(2,course);
                pstt1.executeUpdate();
            }
            if(S12223.isSelected())
            {
                course="SENG 12223 - DATABASE DESIGN AND DEVELOPMENT";
                PreparedStatement pstt2 =DBC.getConnection().prepareStatement("INSERT INTO Subject VALUES (?,?)");
                pstt2.setString(1,stno);
                pstt2.setString(2,course);
                pstt2.executeUpdate();
            }
            if(S12223.isSelected())
            {
                course="SENG 12213 - DATA STRUCTURES AND ALGORITHM";
                PreparedStatement pstt3 =DBC.getConnection().prepareStatement("INSERT INTO Subject VALUES (?,?)");
                pstt3.setString(1,stno);
                pstt3.setString(2,course);
                pstt3.executeUpdate();
            }
            if(S12242.isSelected())
            {
                course="SENG 12242 - MANAGEMENT FOR ENGINEERING";
                PreparedStatement pstt4 =DBC.getConnection().prepareStatement("INSERT INTO Subject VALUES (?,?)");
                pstt4.setString(1,stno);
                pstt4.setString(2,course);
                pstt4.executeUpdate();
            }
            */
            
            for(i=0;i<count;i++)
            {
                PreparedStatement pstt4 =DBC.getConnection().prepareStatement("INSERT INTO Subject VALUES (?,?)");
                pstt4.setString(1,stno);
                pstt4.setString(2,cs[i]);
                pstt4.executeUpdate();
                
            }
            
            JOptionPane.showMessageDialog(this, "Successfully Registered", "SignUP", 2);
            
            //Statement stmt=DBC.getConnection().createStatement();
            //ResultSet rs=stmt.executeQuery("SELECT * FROM Student WHERE Stu_no='"+stno+"' AND Password='"+pass+"'");
            new Studetail(stno,pass).setVisible(true);
            this.dispose();
            
            
            DBC.getConnection().close();
            
        }catch(Exception e){ System.out.println(e); 
        JOptionPane.showMessageDialog(this, "Exception ERROR", "SignUP", 2);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "PASSWORDS DO NOT MATCH", "SignUP", 1);
        }
        
    }//GEN-LAST:event_registerActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STSIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STSIGNUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox S12213;
    private javax.swing.JCheckBox S12223;
    private javax.swing.JCheckBox S12233;
    private javax.swing.JCheckBox S12242;
    private javax.swing.JLabel age;
    private javax.swing.JLabel bground;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel contactno;
    private javax.swing.JLabel course;
    private javax.swing.JLabel eg;
    private javax.swing.JLabel email;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pass;
    private javax.swing.JButton register;
    private javax.swing.JLabel repass;
    private javax.swing.JButton reset;
    private javax.swing.JLabel sex;
    private javax.swing.JLabel stno;
    private javax.swing.JTextField tage;
    private javax.swing.JTextField tcontactno;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tname;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JPasswordField trepass;
    private javax.swing.JTextField tstno;
    // End of variables declaration//GEN-END:variables
}
