/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UMS;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author sharvan
 */
public class STSIGNIN extends javax.swing.JFrame {

    /**
     * Creates new form STSIGNIN
     */
    public STSIGNIN() {
        initComponents();
        
        tname.setBackground(new java.awt.Color(0,0,0,1));
        tpass.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eg = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        tpass = new javax.swing.JPasswordField();
        exit = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        signin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        pass = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        u_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 230));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(null);

        eg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eg.setForeground(new java.awt.Color(0, 158, 206));
        eg.setText("eg: SE_2017_037");
        jPanel1.add(eg);
        eg.setBounds(470, 340, 250, 20);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(0, 186, 255));
        back.setText("<");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(719, 10, 50, 23);

        tpass.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        tpass.setForeground(new java.awt.Color(255, 255, 255));
        tpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(tpass);
        tpass.setBounds(470, 400, 250, 30);

        exit.setBackground(new java.awt.Color(0, 0, 0));
        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 186, 255));
        exit.setText("x");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(774, 10, 39, 23);

        msg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        msg.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(msg);
        msg.setBounds(470, 600, 250, 30);

        signin.setBackground(new java.awt.Color(0, 0, 0));
        signin.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        signin.setForeground(new java.awt.Color(0, 186, 255));
        signin.setText("Sign in");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        jPanel1.add(signin);
        signin.setBounds(470, 470, 250, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 136, 205));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("-----NOT REGISTERED YET !!!!-----");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(470, 510, 250, 30);

        register.setBackground(new java.awt.Color(0, 0, 0));
        register.setFont(new java.awt.Font("Bungee Inline", 0, 14)); // NOI18N
        register.setForeground(new java.awt.Color(0, 186, 255));
        register.setText("register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register);
        register.setBounds(470, 550, 250, 30);

        pass.setFont(new java.awt.Font("Bungee Inline", 0, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 136, 205));
        pass.setText("password");
        jPanel1.add(pass);
        pass.setBounds(470, 360, 180, 40);

        tname.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        tname.setForeground(new java.awt.Color(255, 255, 255));
        tname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(tname);
        tname.setBounds(470, 310, 250, 30);

        u_name.setFont(new java.awt.Font("Bungee Inline", 0, 18)); // NOI18N
        u_name.setForeground(new java.awt.Color(0, 136, 205));
        u_name.setText("user name");
        jPanel1.add(u_name);
        u_name.setBounds(470, 270, 180, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharvan\\Pictures\\blue-user-icon.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(460, 20, 260, 260);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharvan\\Pictures\\UOKbgr.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        String username = tname.getText();
        String pass = String.valueOf(tpass.getPassword());
        
        DBConnection DBC = new DBConnection();
        try{
            Statement stmt=DBC.getConnection().createStatement();
            ResultSet rs=stmt.executeQuery("SELECT * FROM Student WHERE Stu_no='"+username+"' AND Password='"+pass+"'");
            if(rs.next())
            {
                new Studetail(username,pass).setVisible(true);
                this.dispose();
            }
            else{
                msg.setText("Incorrect Username Or Password");
                tname.setText(null);
                tpass.setText(null);
            }
            
        }catch(Exception e){ System.out.println(e);    
        }   // TODO add your handling code here:
    }//GEN-LAST:event_signinActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        STSIGNUP Stsu = new STSIGNUP();
        Stsu.setVisible(true);
        Stsu.pack();
        Stsu.setLocationRelativeTo(null);
        Stsu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        SignUP Sp = new SignUP();
        Sp.setVisible(true);
        Sp.pack();
        Sp.setLocationRelativeTo(null);
        Sp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STSIGNIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STSIGNIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STSIGNIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STSIGNIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STSIGNIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel eg;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel pass;
    private javax.swing.JButton register;
    private javax.swing.JButton signin;
    private javax.swing.JTextField tname;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JLabel u_name;
    // End of variables declaration//GEN-END:variables
}
